# Generated by Django 5.0.6 on 2024-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default_image.png",
                null=True,
                upload_to="product_images/",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="images/default_image.png",
                null=True,
                upload_to="supplier_logos/",
            ),
        ),
    ]
